pipeline {
    agent any
    
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        // stage('Audit') {
        //     steps {
        //         sh 'echo "Auditing and updating libraries....."'
        //         sh 'npm audit fix --json'
        //         sh 'npm audit --audit-level=high'
        //     }
        // }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                 sh 'npm start &'
                // sh './jenkins/scripts/deliver.sh'
                // input message: 'Finished using the web site? (Click "Proceed" to continue)'
                // sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
