pipeline {
    
    agent any
    
    environment {
        CI = 'true'
    }

    stages {
    
        stage('SCM & Build') {
            steps {
                sh 'npm install'
            }
        }
    
        stage('Dependency Audit') {
            steps {
                sh 'echo "Auditing and updating libraries....."'
                sh 'npm audit'
                sh 'npm audit fix --json'
                // sh 'npm audit --audit-level=high'
            }
        }
 
        stage('SonarQube SAST') {
            steps {
                sh 'echo "This is where the SonarQube Plugin needs to be integrated"'
                // input message: 'No live SonarQube integration - Click "Proceed to skip"'
            }
        }

        stage('Burp Pro DAST') {
            steps {
                sh 'echo "Requesting scan via Burp API"'
                sh '/home/laurence/apiScan.sh'
            }
        }

        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }

        stage('Deliver') {
            steps {
                 sh 'npm start'
                // sh './jenkins/scripts/deliver.sh'
                // input message: 'Finished using the web site? (Click "Proceed" to continue)'
                // sh './jenkins/scripts/kill.sh'
            }
        }

    }
}
